  [platformio]
src_dir = src

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
platform_packages = framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags = -Ishared

[env:sensor_node]
build_src_filter = +<../sensor_node/src/>
lib_deps =
    jgromes/RadioLib
    wollewald/INA226_WE
    paulstoffregen/OneWire
    milesburton/DallasTemperature

[env:base_station]
build_src_filter = +<../base_station/src/>
lib_deps =
    jgromes/RadioLib
